name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '17'
            java-package: jdk
            
      - name: Create google-services
        run: touch ./app/google-services.json | base64
        
      - name: Putting data inside google-services
        env: 
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./app/google-services.json
        
      - name: Test with Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with: 
            api-level: 29
            disable-animations: true
            script: ./gradlew connectedCheck jacocoTestReport

      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
          name: report 
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Download Test Report Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
