name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
            java-package: jdk
            
      - name: Create google-services
        run: touch ./app/google-services.json | base64
        
      - name: Putting data inside google-services
        env: 
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./app/google-services.json

      - name: Record screenshots
        run: ./gradlew recordPaparazziDebug

      - name: Commit changes
        run: |
          git add .
          git commit -m "Upload recorded screenshot tests"
          git push
